version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - node-network
    tty: true
    ports: 
      - "8080:80"
    depends_on: 
        - node-app

  node-app:
    build: 
      context: ./node
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node server.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      
